swagger: '2.0'
info:
  title:
  description:
  termsOfService:
  version:
host: be4-test.bedita.net
basePath: /
schemes:
  - https
paths:
  /roles:
    get:
      description: Returns roles
      summary: Retrieve a list of roles
      operationId: getRoles
      tags:
        - roles
      consumes:
        - application/json
        - application/vnd.api+json
      produces:
        - application/json
        - application/vnd.api+json
      responses:
        '200':
          description: Successful operation
          schema:
            properties:
              data:
                type: array
                items:
                  required: ['id', 'type']
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                      enum: ['roles']
                    attributes:
                      $ref: '#/definitions/Role'
              links:
                type: object
              meta:
                type: object

    post:
      tags:
        - roles
      summary: Create role
      description: Role creation
      operationId: createRole
      produces:
        - application/json
        - application/vnd.api+json
      parameters:
        - in: body
          name: body
          description: Role data
          required: true
          schema:
            $ref: '#/definitions/NewRoleParam'
      responses:
        '200':
          description: Successful operation
          schema:
            properties:
              data:
                type: array
                items:
                  required: ['id', 'type']
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                      enum: ['roles']
                    attributes:
                      $ref: '#/definitions/Role'
              links:
                type: object
              meta:
                type: object
        '400':
          description: Invalid data supplied


definitions:
  NewRoleParam:
    properties:
      data:
        required: [ "type", "attributes" ]
        properties:
          type:
            type: string
            enum: ['roles']
          attributes:
            $ref: '#/definitions/Role'
  Role:
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      unchangeable:
        type: boolean
      created:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time
