swagger: '2.0'
info:
  title:
  description:
  termsOfService:
  version:
host: be4-test.bedita.net
basePath: /
schemes:
  - https
paths:
  /trash:
    get:
      description: Returns objects in trash
      summary: Retrieve a list of objects
      tags:
        - trash
      consumes:
        - application/json
        - application/vnd.api+json
      produces:
        - application/json
        - application/vnd.api+json
      responses:
        '200':
          description: Successful operation
          schema:
            properties:
              data:
                type: array
                items:
                  required: ["id", "type"]
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
              links:
                $ref: '#/definitions/LinkPagination'
              meta:
                $ref: '#/definitions/MetaPagination'

  '/trash/{id}':
    get:
      tags:
        - trash
      summary: Get trash item by id
      description: ''
      produces:
        - application/json
        - application/vnd.api+json
      parameters:
        - name: id
          in: path
          description: 'The id of the trash item to be fetched.'
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            properties:
              data:
                required: ["id", "type"]
                properties:
                  id:
                    type: integer
                  type:
                    type: string
                  attributes:
                    $ref: '#/definitions/Object'
              links:
                $ref: '#/definitions/Link'
        '404':
          description: Object not found

    patch:
      tags:
        - trash
      summary: Restore item from trash
      description: Restore item from trash
      produces:
        - application/json
        - application/vnd.api+json
      parameters:
        - name: id
          in: path
          description: 'The id of the trash item to be restored.'
          required: true
          type: integer
        - name: object
          in: body
          description: 'Object data.'
          required: true
          schema:
            properties:
              data:
                required: ["id", "type"]
                properties:
                  id:
                    type: integer
                  type:
                    type: string
                    enum: ['objects']
      responses:
        '204':
          description: Successful operation | No content
        '404':
          description: Object not found

    delete:
      tags:
        - trash
      summary: Delete trash object by id
      description: 'Delete object from trash'
      produces:
        - application/json
        - application/vnd.api+json
      parameters:
        - name: id
          in: path
          description: 'The id of the trash item to be deleted.'
          required: true
          type: integer
      responses:
        '204':
          description: Successful operation | No content
        '404':
          description: Object not found

definitions:
  Object:
    properties:
      status:
        type: string
        enum: ['on', 'off', 'draft']
      uname:
        type: string
      locked:
        type: boolean
      created:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time
      published:
        type: string
        format: date-time
      title:
        type: string
      description:
        type: string
      body:
        type: string
      extra:
        type: string
      lang:
        type: string
      created_by:
        type: integer
      modified_by:
        type: integer
      publish_start:
        type: string
        format: date-time
      publish_end:
        type: string
        format: date-time
  Link:
    properties:
      self:
        type: string
      home:
        type: string
  LinkPagination:
    properties:
      self:
        type: string
      home:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string
  MetaPagination:
    properties:
      pagination:
        properties:
          count:
            type: integer
          page:
            type: integer
          page_count:
            type: integer
          page_items:
            type: integer
          page_size:
            type: integer
